name: PR-action
on:
  pull_request:
    branches: [ '**' ]
jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-modules-${{hashFiles('**/yarn.lock')}}
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 18.x
      - name: Install Dependencies & Lint
        run: |
          yarn install --frozen-lockfile
          yarn lint
#          yarn affected:lint --parallel=true --all
